### PR TITLE
Support for simple element "errorMessage" and complex element "responseElements".

### PR DESCRIPTION
**Pull request by baldzern4**
Hi,

I have create a fix for issue #1 .
With this fix the cloudtrail plugin can handle the following elements:
- errorMessage
- responseElements

responseElements is a complex element and contains several other elements. I have added the basic / often used elements in our system:
- consoleLogin
- status
- _return
- description
- renewRole
- exitRole
- device
- volumeId
- instanceId

The fix is already working on our graylog 1.3 system.
BR

### CODE REVIEW

**Comment by baldzern4** [comment]
@bernd can you please have a look at this? This might help everyone to get more details/information from cloudtrail.

**Comment by STRML** [comment]
This worked for us on the latest Graylog 2.0 release.

**Comment by evanccnyc** [comment]
cc: @joschi

**Comment by joschi** [comment]
@baldzern4 Thank you for your contribution to Graylog!

Before we can accept any code from you, we need you to sign our [Contributor License Agreement](https://s3.amazonaws.com/graylog2public/Individual+Contributor+Assignment+Agreement+-+Graylog.pdf). Please send us a signed copy to hello@graylog.com so we can merge your pull request.

This is only required once, no matter how many contributions you make in the future. Thank you for helping us with this unfortunate administrative requirement!

**Comment by baldzern4** [comment]
@joschi : done

**Comment by lennartkoopmann** [comment]
I can confirm that we received and filed the CLA! Thank you very much,

**Comment by joschi** [comment]
LGTM, thanks! 👍

**Comment by lennartkoopmann** [comment]
FYI: I merged this over to the `1.0` branch, too. Thanks!

**Pull request merged**
