### PR TITLE
Add proxy configuration to AWSPluginConfiguration component

### LINKED ISSUE #59: Proxy configuration does not seem to work
The plugin configuration object has a `proxyEnabled` attribute, but it cannot be set anywhere. All AWS calls are checking for this attribute and do not use the configured proxy if it is set to `false` - which it is by default, with now no way to set it to `true`.

I don't know if I'm completely missing something here, but it looks to me like this simply cannot work.

### PR DESCRIPTION
**Pull request by joschi**
The HTTP Proxy setting was "lost" in 0939ef1aa389829e1a27d656f6fc69d79cf217c8.

Fixes #59

### CODE REVIEW

**Comment by lennartkoopmann** [comment]
This is definitely for a 2.4.1 release. I changed the milestone. @dennisoelkers  can you review ASAP so we can get 2.4.1 out quick?

**Comment by joschi** [comment]
@lennartkoopmann This PR is for `master`, i. e. Graylog 3.0.0.

**Comment by lennartkoopmann** [comment]
Then we should definitely backport it. This is broken in 2.4.0 from what I can see.

**Comment by joschi** [comment]
@lennartkoopmann Our workflow typically is:

1. Fix in `master`
2. Backport to other version branches

**Comment by lennartkoopmann** [comment]
Yepp, let's do that!

**Pull request merged**
