### PR TITLE
initial implementation of S3Input

### PR DESCRIPTION
**Pull request by sherzberg**
This is a WIP PR just to get some early eyes. We use [FluentD](http://docs.fluentd.org/articles/out_s3) to get our logs from servers to S3 and this PR uses S3 Event Notifcations to grab the S3 objects and pipe them into Graylog.

Ideally this PR would also be able to address #15 but needs a little work and testing as we don't use this plugin to pull our ELB logs (yet).

The AWS S3 Input just grabs raw log lines from the S3 objects. We use a combination of Extractors and another Processor plugin we wrote to handle our custom messages (they are just json).

ToDos:
- [x] read uncompressed data (FluentD compresses our data currently)
- [ ] better docs
- [ ] tests

### CODE REVIEW

**Comment by sherzberg** [comment]
I have tested this locally with ELB access logs by setting up SNS Event Notifications -> SQS.

Here is my grok pattern for those that want to try this out:

```
%{TIMESTAMP_ISO8601:timestamp} %{NOTSPACE:loadbalancer} %{IP:client_ip}:%{NUMBER:client_port:int} %{IP:backend_ip}:%{NUMBER:backend_port:int} %{NUMBER:request_processing_time:float} %{NUMBER:backend_processing_time:float} %{NUMBER:response_processing_time:float} %{NUMBER:elb_status_code:int} %{NUMBER:backend_status_code:int} %{NUMBER:received_bytes:int} %{NUMBER:sent_bytes:int} %{QS:request}
```

**Comment by sherzberg** [comment]
@mrzobot yes. This is basically how we use it. The only way for it to read logs though is to have sqs notifications enabled (but this is pretty easy to setup) for any new s3 log files.

How are your logs making it to s3?

**Comment by sherzberg** [comment]
Cool. I have not tested this, but I would assume as long as you have sqs and sns setup properly for s3 event notifications, this would work.

Let me know if you try this out.

**Comment by sherzberg** [comment]
As far as I know, input plugins are meant to be long running things. So this plugin is currently setup to watch for notifications to know what s3 files to pull in.

Maybe we can make a similar plugin to this one or make changes to this plugin to support your model. How would you want to tell this input which files to pick up and process?

**Comment by sherzberg** [comment]
Yea if you use the s3 event notifications (sns and how this plugin is currently built) you get the "grab new files" for free. Just add a new log file to s3 and graylog will process just that new file. Just make sure to write a new file name, for example, we use a timestamp in the filename on each file upload to ensure files are not processed multiple times.

**Comment by SnazzyBootMan** [comment]
This looks like a very useful addition to the AWS Plugin - do we know when it will be merged?

**Comment by sherzberg** [comment]
I'm finally getting back to work on this. Any input from Graylog folks about whether or not this should be included in this repos plugin or if it should just be a separate plugin all together?

**Comment by jalogisch** [comment]
@sherzberg Did you find the time to check if this usefull PR can be merged into the current code and is working with the current plugin?

If not i'll close this PR and will wait for a new PR once you have that working against the actuall source.

Thanks

**Comment by jalogisch** [comment]
I notice that you ( @sherzberg ) release this plugin: https://github.com/sherzberg/graylog-plugin-s3

Without the change to the current master I'll close the PR now.

**Pull request closed without merging**
