### PR TITLE
Include additional_event_data as part of a field

### PR DESCRIPTION
**Pull request by rongutierrez**
Data that is passed along within the 'additionalEventData' fields of the Cloudtrail message are not passed along to the messages sent to Graylog. This Pull Request adds in that additional field. 

One example of important data pass in this value is on the 'ConsoleLogin' event where it specifies whether MFA was used for the login attempt. There could be other cases where alerts could be created on Graylog using data within this field.

### CODE REVIEW

**Comment by rongutierrez** [comment]
Hi, Can anyone please review this pull request?

**Comment by kroepke** [comment]
@waab76 this is the old plugin, correct? can we have a look at the new one to see if this addresses the issue already? Thanks :)

**Comment by waab76** [comment]
The Kinesis/Cloudwatch plugin has moved over to the `graylog-plugin-integrations` repo, but this is repo is still the home of the Cloudtrail plugin (which is what this PR is concerned with).  I'll take a look at this PR.

**Review by waab76 — APPROVED** [review]
LGTM

**Pull request merged**
