### PR TITLE
Update AWS SDK version to latest version

### LINKED ISSUE #118: Check support for AWS US Gov East region
It looks that the library version we are using does not have support for the US Gov East region.
It was added in https://github.com/aws/aws-sdk-java/commit/d617b31353d63a8291ff0be66727ce771ad4c812, referenced in https://github.com/aws/aws-sdk-java/blame/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java#L28 

We are still on an older version, so updating the client version to the latest should quickly fix the issue.

### PR DESCRIPTION
**Pull request by danotorrey**
Fixes #118 

It's also a good practice to keep the AWS SDK up to date.

The following steps need to be performed before this PR is ready for review:
* Verify that they new region is available in the AWS plugin inputs (might need to also make a Graylog code change for that)
* Regression test existing AWS plugin features.

Will need backport.

### CODE REVIEW

**Comment by danotorrey** [comment]
The UI display values for AWS regions has also been cleaned up with this PR:

Before:
Screen Shot 2019-04-08 at 4 59 00 PM

After:
Screen Shot 2019-04-08 at 4 56 47 PM

**Comment by danotorrey** [comment]
The only remaining step is to spot regression test the new SDK client version. Working on this now.

**Comment by garybot2** [comment]
Looks like we would not be able to merge this PR because of merge conflicts. Please rebase, fix conflicts, and force push to your branch.

**Comment by danotorrey** [comment]
@bernd Ready for review. I have regression tested the AWS Flow Logs and AWS Cloud Trail inputs. All works successfully with the new versions.

I am not sure how to dismiss the is-mergable check. https://github.com/Graylog2/graylog-plugin-aws/pull/121/commits/d2b1903a1ba2be55541e9c0947efd8f420ce5ec5 was created by Dependabot. I merged it into this PR, but the check won't dismiss. Do you know how to get it to re-run that check?

We will want to include this in 3.0.2, so I added to the Stable Release Backports project.

// FYI to @kroepke that this is done. I will also let Taylor know that we plan to release this within the next weeks, so she can follow up with the customer.

**Comment by bernd** [comment]
@danotorrey That check can only be re-triggered by pushing something. But we can also just ignore it. :wink:

**Pull request merged**
